ARG BALENA_MACHINE_NAME="%%BALENA_MACHINE_NAME%%"
FROM balenalib/${BALENA_MACHINE_NAME}-python:3.8 as runner
COPY requirements.txt /reqs.txt
RUN pip3 install -r /reqs.txt && rm -f /reqs.txt
COPY src /app
EXPOSE 8000
ENTRYPOINT ["uvicorn", "app.main:app", "--host", "0.0.0.0"]